from crewai import Agent, Task, Crew, Process

researcher = Agent(
    role="Lead Technology Researcher",
    goal="Uncover cutting-edge developments, verified facts, and key trends on {topic}",
    backstory=(
        "You are an analytical researcher with a keen eye for detail. "
        "You specialize in sifting through noise to find credible sources, "
        "reputable statistics, and breakthrough updates on complex technical subjects."
    ),
    verbose=True,
    allow_delegation=False
)

writer = Agent(
    role="Senior Content Writer",
    goal="Draft an engaging, easy-to-read, and educational article about {topic}",
    backstory=(
        "You are a skilled wordsmith who excels at simplifying complex technical ideas. "
        "You know how to structure an article to hook readers, using compelling analogies "
        "while ensuring the final draft remains highly informative and accurate."
    ),
    verbose=True,
    allow_delegation=False
)

editor = Agent(
    role="Managing Editor",
    goal="Polish and refine the article on {topic} for tone, clarity, and grammatical perfection",
    backstory=(
        "You are a meticulous editor who maintains a high bar for editorial standards. "
        "Your job is to ensure the voice is professional yet engaging, formatting is clean, "
        "and the overall narrative flows flawlessly from beginning to end."
    ),
    verbose=True,
    allow_delegation=False
)


research_task = Task(
    description=(
        "Conduct thorough research on the following topic: {topic}. "
        "Identify the core concepts, major benefits, real-world use cases, and current trends. "
        "Provide a comprehensive outline of verified findings."
    ),
    expected_output=(
        "A detailed, bulleted markdown document containing raw facts, key statistics, "
        "and structured topic summaries. Keep it clean and highly structured."
    ),
    agent=researcher
)

writer_task = Task(
    description=(
        "Using the structured notes provided by the Lead Technology Researcher, "
        "write an engaging and informative article about {topic}. "
        "Ensure the text is accessible to a broad audience, uses formatting (like headers and lists) "
        "to improve readability, and remains true to the researched facts."
    ),
    expected_output=(
        "A full-length draft of the article in Markdown format, complete with an "
        "attention-grabbing introduction, body paragraphs with clear subheaders, and a conclusion."
    ),
    agent=writer
)

editor_task = Task(
    description=(
        "Review and refine the draft article generated by the Senior Content Writer. "
        "Check for grammatical errors, verify that the tone is consistent, ensure smooth transitions, "
        "and format the document professionally."
    ),
    expected_output=(
        "The finalized, polished article in pristine Markdown format, fully ready for publication."
    ),
    agent=editor
)

content_creation_crew = Crew(
    agents=[researcher,writer,editor],
    tasks=[research_task,writer_task,editor_task],
    process=Process.sequential,
    verbose=True
)


print("/CONTENT CREATOR RESEACRH AGENT\\")
# user_input = input("User: ")

input = {
    "topic": "Model Context Protocol (MCP) in Multi-Agent Workflows"
}

print(content_creation_crew.kickoff(inputs=input))